networks:
  backend:
    name: my-postgres-network

services:
  my-postgres-service:
    container_name: my-postgres-container
    # SEE version: https://hub.docker.com/_/postgres/
    image: postgres:18.1-alpine3.23
    networks: [backend]
    ports: ["5432:5432"]
    volumes:
      - ./container-data/postgres:/data/postgres
      # NOTE: this migration runs only once on container creation.
      - ./initial-migration/:/docker-entrypoint-initdb.d/
    env_file: [./.postgres.env]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s

