START TRANSACTION;

CREATE TABLE IF NOT EXISTS pg_migrations (
	id serial PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	file_id VARCHAR UNIQUE NOT NULL
);

INSERT INTO pg_migrations (file_id) VALUES ('00000');

COMMIT;
